### PR TITLE
Add contributors' details

### PR DESCRIPTION
**Pull request by harrietrs**

### CODE REVIEW

**Comment by Mbajwa15** [comment]
Hi Harriet how do I start on this I have pyspark and have used padas libraries but don't know how to do this

**Comment by harrietrs** [comment]
> Hi Harriet how do I start on this I have pyspark and have used padas libraries but don't know how to do this

Hi! Could you tell me what you're trying to do? Is this connected to this pull request?

**Comment by harrietrs** [comment]
Hi @Mbajwa15 - I've been told by the team that you've also reached out via email? The team will get back to you via that route shortly! Thanks

**Comment by harrietrs** [comment]
> Hi @Mbajwa15 - I've been told by the team that you've also reached out via email? The team will get back to you via that route shortly! Thanks

I'm also going to delete your comment as it contains your email info etc., please reach out if that's not ok

**Comment by Mbajwa15** [comment]
That’s fine thank you Harriet - 😊

**Pull request merged**
